Changed status code to follow conventions and some documentation fixes
michael-mosler/Pius-App-Gateway pull request #8
Opened 2020-12-17 20:03 UTC by Taucher2003

I made some changes and will explain why I made them.

## Status codes

Some routes return the 200 status code which means OK but don't return any content. When a request returns no content they should use the 204 status code so it states that it returns no content.

This change may require some changes in the app if you expect the 200 status instead of the full 2xx range.

## Documentation

`server/core-services/CloudantConnection.js` removed a double space
`server/core-services/CloudantDb.js` changed rettry to retry
`server/data-objects/EvaServiceData.js` changed hsitory to history

2020-12-18 22:52 UTC, Th3Ph4nt0m approved these changes
Looks good!

2021-02-25 19:54 UTC, michael-mosler commented on server/core-services/DeviceTokenManager.js
> +          .then(() => res.status(204).end())
This is a breaking change that will cause app to stop working completely. Device tokens are registered with every restart of the app. When app receives another code than 200 at least iOS version is reporting this as an error.

I agree, 204 would be the correct response code. But with apps in the wild we need to introduce a new version of DeviceToken endpoint.

2021-02-25 19:56 UTC, michael-mosler requested changes
Sorry for not noticing this PR. I did not expect the Spanish Inquisition (small Monty Python insider). I fear that changing the response code in DeviceToken endpoint is a breaking change. See my comment below. In fact a version of the endpoint will be needed to correct this. We need to consider if it is worth the effort.

2021-02-26 09:07 UTC, Taucher2003 commented on server/core-services/DeviceTokenManager.js
> +          .then(() => res.status(204).end())
Then I will probably revert this change in favor of the current version of the apps

2021-02-26 12:20 UTC, michael-mosler requested changes
Sorry for getting back to you again. But there is a new code location in the same function which also now return 204 instead of 200. You also should update comment, please.

Thanks!
Michael

2021-03-17 08:03 UTC, michael-mosler approved these changes

2021-03-21 10:25 UTC, merged